/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: sgx-linux-x86_64"
#define DATE "built on: Thu Dec  7 13:33:32 2023 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','g','c','c',' ','-','f',
    'P','I','C',' ','-','p','t','h','r','e','a','d',' ','-','m','6',
    '4',' ','-','W','a',',','-','-','n','o','e','x','e','c','s','t',
    'a','c','k',' ','-','W','a','l','l',' ','-','O','3',' ','-','g',
    ' ','-','i','n','c','l','u','d','e','/','d','a','t','a','/','k',
    'a','j','e','t','a','n','/','r','e','p','o','/','g','r','a','p',
    'h','o','s','-','j','a','v','a','d','/','O','m','i','x','+','+',
    '/','s','g','x','s','s','l','/','L','i','n','u','x','/','.','.',
    '/','o','p','e','n','s','s','l','_','s','o','u','r','c','e','/',
    'b','y','p','a','s','s','_','t','o','_','s','g','x','s','s','l',
    '.','h',' ','-','D','O','P','E','N','S','S','L','_','U','S','E',
    '_','N','O','D','E','L','E','T','E',' ','-','D','L','_','E','N',
    'D','I','A','N',' ','-','D','O','P','E','N','S','S','L','_','P',
    'I','C',' ','-','D','O','P','E','N','S','S','L','_','B','U','I',
    'L','D','I','N','G','_','O','P','E','N','S','S','L',' ','-','D',
    'N','D','E','B','U','G',' ','-','D','_','F','O','R','T','I','F',
    'Y','_','S','O','U','R','C','E','=','2',' ','-','D','G','E','T',
    'P','I','D','_','I','S','_','M','E','A','N','I','N','G','L','E',
    'S','S','\0'
};
